## Python practice

Day 1 - 29/09

In [ ]:
# --- LISTS PRACTICE ---
import numpy as np
# 1. Delete element at index 5 from list x
x_l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
del x_l[5]
print(x_l)

# 2. What happens with [1,1] + [1,1] ?
x = (np.asarray([1,1]))
y = (np.asarray([1,1]))
z = x + y
print(z)


# 4. Create a copy of list x two ways:
#    y = list(x)
#    y = x[:]

y = list(x)
y = x[:]
# 5. Find the index of "python" in a list of strings
strings = ["This", "is", "python"]

strings.index("python")
# 6. Count occurrences of number 2 in a list ???
# np.bincount(x, 2)
print(x_l.count(2))
# 7. Append "new" to a list
strings.append("new")
print(strings)
# 8. Reverse a list called areas
print(strings.reverse())

x = [1, 2, 3, 4, 5]
y = x[::-1]   # makes a reversed *copy*
print(y)  # [5, 4, 3, 2, 1]

# 9. Remove the first occurrence of 5 in list x
x2 = x_l[5:]
print(x2)
# 10. Insert "Gloomhaven" at index 0 in boardgames
boardgames = ["Cluedo", "Monopoly"]
boardgames.insert(0,"Gloomhaven")
print(boardgames)

[1, 2, 3, 4, 5, 7, 8, 9]
[2 2]
1
['This', 'is', 'python', 'new']
None
[7, 8, 9]
['Gloomhaven', 'Cluedo', 'Monopoly']


In [24]:
# --- STRINGS PRACTICE ---

# 1. Capitalize the first letter of a string
print("Daniel".capitalize())
# 2. Replace all "a" with "abc" in a string
print("banana".replace("a", "abc"))
# 3. Find the index of "a" in a string
print("banana".index("a"))
# 4. Count how many "o" appear in "Toronto"
print("Totonto".count("o"))

Daniel
babcnabcnabc
1
3


In [54]:
import numpy as np

# --- NUMPY PRACTICE ---

# 1. Given bmi = np.array([...]), test if bmi > 23

bmi = np.array([21, 24, 19, 28, 23, 15, 36])

print(bmi>23)
# 2. Return only the values of bmi where bmi > 23
bmi[bmi>23]
# 3. Show attributes:
bmi.shape

# 4. Correlation: np.corrcoef(array1, array2)
height = np.asarray([192, 202, 165, 120])
weight = np.asarray([80, 90, 65, 50])

print(np.corrcoef(height,weight))
# 5. Try np.sum(x) and np.sort(bmi)
print(np.sum(height))
weight2 = np.sort(weight)
print(weight2)
# 6. Combine arrays a1 and a2 with np.column_stack
print(np.column_stack((height, weight)))
print(np.vstack((height, weight)))

# 7. Iterate through an array with np.nditer
x_3D = np.asarray([[1,2,3],[2,3,4],[3,4,5]])
for x in np.nditer(x_3D):
    print(x)

for x in x_3D:
    print(x)

# 9. Transpose np_aw
print(np.transpose(x_3D))

[False  True False  True False False  True]
[[1.       0.979941]
 [0.979941 1.      ]]
679
[50 65 80 90]
[[192  80]
 [202  90]
 [165  65]
 [120  50]]
[[192 202 165 120]
 [ 80  90  65  50]]
1
2
3
2
3
4
3
4
5
[1 2 3]
[2 3 4]
[3 4 5]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [33]:
# --- MATPLOTLIB PRACTICE ---
import matplotlib.pyplot as plt


import matplotlib.pyplot as plt

# --- DATA SETUP (for practice) ---
life_exp = [50, 55, 60, 62, 65, 70, 72, 75, 80, 82]
gdp_cap = [1000, 2000, 3000, 4000, 5000, 6000, 10000, 3000, 1000, 2000]
np_pop = [10, 20, 30, 40, 50, 60, 20, 1, 23, 34]
tick_val = [50, 60, 70, 80]
tick_lab = ["50 yrs", "60 yrs", "70 yrs", "80 yrs"]

# --- MATPLOTLIB PRACTICE ---

# 1. Clean the current figure
# 2. Create a histogram of life_exp with 15 bins
# plt.hist(life_exp, bins=5)
# # 3. Set custom x-ticks with tick_val and tick_lab
# plt.xticks(tick_val, tick_lab)
# 4. Create a bubble scatter plot with gdp_cap, life_exp, and np_pop as sizes
# plt.scatter(gdp_cap, life_exp, s=np_pop, c="r", alpha = 0.4)
# # 5. Add the label "China" at (5700, 80)
# plt.text(5000, 65, "China")
# # 6. Add gridlines to the plot
# plt.grid(True)

europe = {
    "spain": {"capital": "madrid", "population": 46.77},
    "france": {"capital": "paris", "population": 66.03}
}
world = {"china": 1.38, "india": 1.29}

names = ["spain", "france", "germany"]
dr = [True, True, False]
cpc = [500, 600, 700]

# --- DICTIONARY PRACTICE ---

# 7. List the keys of the dictionary europe
# europe.keys()
# 8. Are keys, strings, booleans, and integers mutable or immutable?
# immutable
# 9. Check if "sealand" is a key in the dictionary world
# "china" in world
# 10. Add a new entry "sealand": 0.000027 to world
world["sealand"] = 0.000027
print(world)
# 11. Delete "sealand" from world
del(world["sealand"])
print(world)
# 12. Define a nested dictionary entry for Spain with capital Madrid and population 46.77
europe = {"spain" : {"capital": "madrid", "pop": 46.77}}
print(europe)
# 13. Create a dictionary with keys country, drives_right, and cars_per_cap
my_dict = ({"country":names, "drives_right":dr, "cars_per_cap":cpc})
print(my_dict)
# 14. Iterate through keys and values in a dictionary
for key in my_dict.values():
    print(key)

{'china': 1.38, 'india': 1.29, 'sealand': 2.7e-05}
{'china': 1.38, 'india': 1.29}
{'spain': {'capital': 'madrid', 'pop': 46.77}}
{'country': ['spain', 'france', 'germany'], 'drives_right': [True, True, False], 'cars_per_cap': [500, 600, 700]}
['spain', 'france', 'germany']
[True, True, False]
[500, 600, 700]
