## Python practice

Day 1 - 29/09

In [ ]:
# --- LISTS PRACTICE ---
import numpy as np
# 1. Delete element at index 5 from list x
x_l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
del x_l[5]
print(x_l)

# 2. What happens with [1,1] + [1,1] ?
x = (np.asarray([1,1]))
y = (np.asarray([1,1]))
z = x + y
print(z)


# 4. Create a copy of list x two ways:
#    y = list(x)
#    y = x[:]

y = list(x)
y = x[:]
# 5. Find the index of "python" in a list of strings
strings = ["This", "is", "python"]

strings.index("python")
# 6. Count occurrences of number 2 in a list ???
# np.bincount(x, 2)
print(x_l.count(2))
# 7. Append "new" to a list
strings.append("new")
print(strings)
# 8. Reverse a list called areas
print(strings.reverse())

x = [1, 2, 3, 4, 5]
y = x[::-1]   # makes a reversed *copy*
print(y)  # [5, 4, 3, 2, 1]

# 9. Remove the first occurrence of 5 in list x
x2 = x_l[5:]
print(x2)
# 10. Insert "Gloomhaven" at index 0 in boardgames
boardgames = ["Cluedo", "Monopoly"]
boardgames.insert(0,"Gloomhaven")
print(boardgames)

[1, 2, 3, 4, 5, 7, 8, 9]
[2 2]
1
['This', 'is', 'python', 'new']
None
[7, 8, 9]
['Gloomhaven', 'Cluedo', 'Monopoly']


In [24]:
# --- STRINGS PRACTICE ---

# 1. Capitalize the first letter of a string
print("Daniel".capitalize())
# 2. Replace all "a" with "abc" in a string
print("banana".replace("a", "abc"))
# 3. Find the index of "a" in a string
print("banana".index("a"))
# 4. Count how many "o" appear in "Toronto"
print("Totonto".count("o"))

Daniel
babcnabcnabc
1
3


In [54]:
import numpy as np

# --- NUMPY PRACTICE ---

# 1. Given bmi = np.array([...]), test if bmi > 23

bmi = np.array([21, 24, 19, 28, 23, 15, 36])

print(bmi>23)
# 2. Return only the values of bmi where bmi > 23
bmi[bmi>23]
# 3. Show attributes:
bmi.shape

# 4. Correlation: np.corrcoef(array1, array2)
height = np.asarray([192, 202, 165, 120])
weight = np.asarray([80, 90, 65, 50])

print(np.corrcoef(height,weight))
# 5. Try np.sum(x) and np.sort(bmi)
print(np.sum(height))
weight2 = np.sort(weight)
print(weight2)
# 6. Combine arrays a1 and a2 with np.column_stack
print(np.column_stack((height, weight)))
print(np.vstack((height, weight)))

# 7. Iterate through an array with np.nditer
x_3D = np.asarray([[1,2,3],[2,3,4],[3,4,5]])
for x in np.nditer(x_3D):
    print(x)

for x in x_3D:
    print(x)

# 9. Transpose np_aw
print(np.transpose(x_3D))

[False  True False  True False False  True]
[[1.       0.979941]
 [0.979941 1.      ]]
679
[50 65 80 90]
[[192  80]
 [202  90]
 [165  65]
 [120  50]]
[[192 202 165 120]
 [ 80  90  65  50]]
1
2
3
2
3
4
3
4
5
[1 2 3]
[2 3 4]
[3 4 5]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
